### ISSUE TITLE
Can't start docker nginx container

### ISSUE THREAD

**Issue by woduda** [frantiq90/exchange-rate-app#1]
Problem when starting containers:
```
nginx_1      | 2020/11/01 11:58:45 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
```
I suggest adding nginx folder in logs/ with .keepgit file ;)

**Comment by frantiq90** [comment]
Thanks for reporting. Issue should be resolved now. Could you please check that you can start container?

**Comment by woduda** [comment]
It works perfect now. Closing..
